import { apiClient } from "./client";
import type { AuditEntry, Notification, Permission, Role, User } from "../types";
export const adminApi = {
  getUsers: () => apiClient.get<User[]>("/admin/users").then(r=>r.data),
  createUser: (d: {first_name:string;last_name:string;middle_name?:string;email:string;password:string;role_ids:string[]}) => apiClient.post<User>("/admin/users", d).then(r=>r.data),
  getUser: (id: string) => apiClient.get<User>(`/admin/users/${id}`).then(r=>r.data),
  updateUser: (id: string, d: object) => apiClient.put<User>(`/admin/users/${id}`, d).then(r=>r.data),
  activateUser: (id: string) => apiClient.patch<User>(`/admin/users/${id}/activate`).then(r=>r.data),
  deactivateUser: (id: string) => apiClient.patch<User>(`/admin/users/${id}/deactivate`).then(r=>r.data),
  deleteUser: (id: string) => apiClient.delete(`/admin/users/${id}`),
  setPassword: (id: string, pw: string) => apiClient.post(`/admin/users/${id}/set-password`, {new_password: pw}),
  logoutAll: (id: string) => apiClient.post(`/admin/users/${id}/logout-all`),
  getUserRoles: (id: string) => apiClient.get<{user_id:string;roles:Role[]}>(`/admin/users/${id}/roles`).then(r=>r.data),
  assignRoles: (id: string, role_ids: string[]) => apiClient.post(`/admin/users/${id}/roles`, {role_ids}).then(r=>r.data),
  getRoles: () => apiClient.get<Role[]>("/admin/roles").then(r=>r.data),
  createRole: (d: object) => apiClient.post<Role>("/admin/roles", d).then(r=>r.data),
  updateRole: (id: string, d: object) => apiClient.put<Role>(`/admin/roles/${id}`, d).then(r=>r.data),
  deleteRole: (id: string) => apiClient.delete(`/admin/roles/${id}`),
  getRolePermissions: (id: string) => apiClient.get<Permission[]>(`/admin/roles/${id}/permissions`).then(r=>r.data),
  assignPermissionsToRole: (id: string, permission_ids: string[]) => apiClient.post(`/admin/roles/${id}/permissions`, {permission_ids}),
  getPermissions: () => apiClient.get<Permission[]>("/admin/permissions").then(r=>r.data),
  createPermission: (d: object) => apiClient.post<Permission>("/admin/permissions", d).then(r=>r.data),
  updatePermission: (id: string, description: string) => apiClient.put<Permission>(`/admin/permissions/${id}`, {description}).then(r=>r.data),
  deletePermission: (id: string) => apiClient.delete(`/admin/permissions/${id}`),
  getNotifications: (unread?: boolean) => apiClient.get<Notification[]>(`/admin/notifications${unread?"?unread_only=true":""}`).then(r=>r.data),
  getUnreadCount: () => apiClient.get<{count:number}>("/admin/notifications/unread-count").then(r=>r.data),
  markRead: (id: string) => apiClient.patch(`/admin/notifications/${id}/read`),
  markAllRead: () => apiClient.patch("/admin/notifications/read-all"),
  getAuditLog: (params?: object) => apiClient.get<AuditEntry[]>("/admin/audit-log", {params}).then(r=>r.data),
};
